import { Expense, Settlement, User, RecurringBill, HouseholdSettings, AppNotification } from "@/types";

export const INITIAL_USERS: User[] = [
  {
    id: "user-salman",
    name: "Salman",
    email: "salman@housemint.local",
    accent_color: "user-1",
    role: "admin",
    is_roommate: true,
  },
  {
    id: "user-alex",
    name: "Alex",
    email: "alex@housemint.local",
    accent_color: "user-2",
    role: "member",
    is_roommate: true,
  },
  {
    id: "user-tanvir",
    name: "Tanvir",
    email: "tanvir@housemint.local",
    accent_color: "user-1",
    role: "member",
    is_roommate: true,
  },
  {
    id: "user-rahim",
    name: "Rahim",
    email: "rahim@housemint.local",
    accent_color: "user-2",
    role: "member",
    is_roommate: true,
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: "exp-1",
    title: "Apartment Rent — August",
    category: "rent",
    amount: 24000,
    paid_by: "user-salman",
    date: "2026-08-01",
    split_type: "equal",
    is_recurring: true,
    recurring_bill_id: "rec-rent",
    notes: "Monthly 3-bed apartment rent paid to landlord",
    splits: [
      { user_id: "user-salman", amount: 6000, percentage: 25 },
      { user_id: "user-alex", amount: 6000, percentage: 25 },
      { user_id: "user-tanvir", amount: 6000, percentage: 25 },
      { user_id: "user-rahim", amount: 6000, percentage: 25 },
    ],
    created_at: "2026-08-01T10:00:00Z",
  },
  {
    id: "exp-2",
    title: "Weekly Grocery Haul (Shwapno)",
    category: "groceries",
    amount: 4800,
    paid_by: "user-alex",
    date: "2026-08-05",
    split_type: "equal",
    notes: "Rice, chicken, vegetables, milk, cooking oil for apartment",
    items: [
      {
        id: "item-1",
        name: "Miniket Rice (10kg)",
        quantity: 2,
        unit: "pack",
        unit_price: 420,
        total_price: 840,
      },
      {
        id: "item-2",
        name: "Broiler Chicken",
        quantity: 4,
        unit: "kg",
        unit_price: 220,
        total_price: 880,
      },
      {
        id: "item-3",
        name: "Rupchanda Soybean Oil (5L)",
        quantity: 1,
        unit: "bottle",
        unit_price: 980,
        total_price: 980,
      },
      {
        id: "item-4",
        name: "Fresh Milk & Yogurt",
        quantity: 6,
        unit: "litre",
        unit_price: 100,
        total_price: 600,
      },
      {
        id: "item-5",
        name: "Mixed Fresh Vegetables & Spices",
        quantity: 1,
        unit_price: 1500,
        total_price: 1500,
      },
    ],
    splits: [
      { user_id: "user-salman", amount: 1200, percentage: 25 },
      { user_id: "user-alex", amount: 1200, percentage: 25 },
      { user_id: "user-tanvir", amount: 1200, percentage: 25 },
      { user_id: "user-rahim", amount: 1200, percentage: 25 },
    ],
    created_at: "2026-08-05T14:30:00Z",
  },
  {
    id: "exp-3",
    title: "Fiber Internet Bill (100 Mbps)",
    category: "internet",
    amount: 2000,
    paid_by: "user-tanvir",
    date: "2026-08-08",
    split_type: "equal",
    is_recurring: true,
    recurring_bill_id: "rec-internet",
    splits: [
      { user_id: "user-salman", amount: 500, percentage: 25 },
      { user_id: "user-alex", amount: 500, percentage: 25 },
      { user_id: "user-tanvir", amount: 500, percentage: 25 },
      { user_id: "user-rahim", amount: 500, percentage: 25 },
    ],
    created_at: "2026-08-08T11:15:00Z",
  },
  {
    id: "exp-4",
    title: "Electricity (DPDC Prepaid Meter Recharge)",
    category: "electricity",
    amount: 3200,
    paid_by: "user-rahim",
    date: "2026-08-14",
    split_type: "equal",
    notes: "Living room & bedroom AC usage",
    splits: [
      { user_id: "user-salman", amount: 800, percentage: 25 },
      { user_id: "user-alex", amount: 800, percentage: 25 },
      { user_id: "user-tanvir", amount: 800, percentage: 25 },
      { user_id: "user-rahim", amount: 800, percentage: 25 },
    ],
    created_at: "2026-08-14T16:45:00Z",
  },
  {
    id: "exp-5",
    title: "Gas Cylinder Refill (LPG 12kg)",
    category: "gas",
    amount: 1400,
    paid_by: "user-salman",
    date: "2026-08-18",
    split_type: "equal",
    splits: [
      { user_id: "user-salman", amount: 350, percentage: 25 },
      { user_id: "user-alex", amount: 350, percentage: 25 },
      { user_id: "user-tanvir", amount: 350, percentage: 25 },
      { user_id: "user-rahim", amount: 350, percentage: 25 },
    ],
    created_at: "2026-08-18T09:20:00Z",
  },
  {
    id: "exp-6",
    title: "Mid-month Fresh Market & Snacks",
    category: "groceries",
    amount: 2400,
    paid_by: "user-alex",
    date: "2026-08-22",
    split_type: "equal",
    items: [
      {
        id: "item-6",
        name: "Eggs",
        quantity: 4,
        unit: "dozen",
        unit_price: 165,
        total_price: 660,
      },
      {
        id: "item-7",
        name: "Fruits (Apples & Bananas)",
        quantity: 3,
        unit: "kg",
        unit_price: 240,
        total_price: 720,
      },
      {
        id: "item-8",
        name: "Tea, Biscuits & Snacks",
        quantity: 4,
        unit: "pack",
        unit_price: 255,
        total_price: 1020,
      },
    ],
    splits: [
      { user_id: "user-salman", amount: 600, percentage: 25 },
      { user_id: "user-alex", amount: 600, percentage: 25 },
      { user_id: "user-tanvir", amount: 600, percentage: 25 },
      { user_id: "user-rahim", amount: 600, percentage: 25 },
    ],
    created_at: "2026-08-22T18:10:00Z",
  },
];

export const INITIAL_SETTLEMENTS: Settlement[] = [
  {
    id: "set-1",
    payer_id: "user-tanvir",
    receiver_id: "user-salman",
    amount: 5000,
    date: "2026-08-10",
    notes: "Rent share settlement via bKash",
    created_at: "2026-08-10T19:00:00Z",
  },
];

export const INITIAL_RECURRING_BILLS: RecurringBill[] = [
  {
    id: "rec-rent",
    title: "Apartment Rent",
    category: "rent",
    default_amount: 24000,
    billing_cycle: "monthly",
    due_day_of_month: 1,
    default_payer_id: "user-salman",
    split_type: "equal",
    participant_ids: ["user-salman", "user-alex", "user-tanvir", "user-rahim"],
    is_active: true,
    notes: "Monthly 3-bedroom apartment rent paid to landlord",
    created_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "rec-internet",
    title: "Fiber Internet Bill",
    category: "internet",
    default_amount: 2000,
    billing_cycle: "monthly",
    due_day_of_month: 8,
    default_payer_id: "user-tanvir",
    split_type: "equal",
    participant_ids: ["user-salman", "user-alex", "user-tanvir", "user-rahim"],
    is_active: true,
    notes: "100 Mbps shared fiber optical line",
    created_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "rec-gas",
    title: "Gas Cylinder Refill (LPG)",
    category: "gas",
    default_amount: 1400,
    billing_cycle: "monthly",
    due_day_of_month: 15,
    default_payer_id: "user-salman",
    split_type: "equal",
    participant_ids: ["user-salman", "user-alex", "user-tanvir", "user-rahim"],
    is_active: true,
    notes: "12kg cylinder delivery for kitchen stove",
    created_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "rec-electricity",
    title: "DESCO Electricity Bill",
    category: "electricity",
    default_amount: 3200,
    billing_cycle: "monthly",
    due_day_of_month: 25,
    default_payer_id: "user-rahim",
    split_type: "equal",
    participant_ids: ["user-salman", "user-alex", "user-tanvir", "user-rahim"],
    is_active: true,
    notes: "Postpaid building electric meter bill",
    created_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "rec-service",
    title: "Apartment Building Service & Guard Fee",
    category: "other",
    default_amount: 2500,
    billing_cycle: "monthly",
    due_day_of_month: 30,
    default_payer_id: "user-alex",
    split_type: "equal",
    participant_ids: ["user-salman", "user-alex", "user-tanvir", "user-rahim"],
    is_active: true,
    notes: "Elevator maintenance, security guard, waste disposal",
    created_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "rec-maid",
    title: "Housekeeper / Cook Salary",
    category: "other",
    default_amount: 6000,
    billing_cycle: "monthly",
    due_day_of_month: 5,
    default_payer_id: "user-rahim",
    split_type: "equal",
    participant_ids: ["user-salman", "user-alex", "user-tanvir", "user-rahim"],
    is_active: true,
    notes: "Monthly cooking and cleaning service",
    created_at: "2026-08-01T00:00:00Z",
  },
];

export const INITIAL_HOUSEHOLD_SETTINGS: HouseholdSettings = {
  householdName: "Flat 4B — Dhanmondi",
  inviteCode: "MINT-4B",
  adminInviteCode: "MINT-ADMIN-4B",
  defaultSplitMode: "equal",
  landlordName: "Alhaj Rafiqul Islam",
  landlordPhone: "+880 1711-234567",
  landlordPaymentMethod: "bKash (01711234567) / City Bank A/C 204128912",
  electricityMeterNo: "DESCO Pre-paid #1420993821",
  internetClientId: "Carnival Broadband User ID: DH-DHM-402",
  emergencyFundEnabled: false,
  emergencyFundBalance: 0,
  lockedMonths: ["2026-07"],
};

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif-1",
    actor_id: "user-salman",
    actor_name: "Salman",
    action_type: "expense_created",
    title: "Grocery Added",
    description: "Salman added 'Weekly Grocery Haul (Shwapno)' (৳4,800)",
    amount: 4800,
    category: "groceries",
    target_id: "exp-2",
    target_title: "Weekly Grocery Haul (Shwapno)",
    created_at: "2026-08-04T18:30:00Z",
    read_by: [],
  },
  {
    id: "notif-2",
    actor_id: "user-tanvir",
    actor_name: "Tanvir",
    action_type: "settlement_created",
    title: "Debt Settled",
    description: "Tanvir recorded settlement of ৳5,000 to Salman",
    amount: 5000,
    target_id: "set-1",
    created_at: "2026-08-10T19:00:00Z",
    read_by: [],
  },
  {
    id: "notif-3",
    actor_id: "user-alex",
    actor_name: "Alex",
    action_type: "recurring_bill_logged",
    title: "Internet Bill Logged",
    description: "Alex paid 'High-Speed Fiber Internet' (৳2,000)",
    amount: 2000,
    category: "internet",
    target_id: "exp-3",
    created_at: "2026-08-05T12:00:00Z",
    read_by: [],
  },
];
